// angular/src/app/shared/components/ui/ui-loading-spinner/ui-loading-spinner.component.ts
import { Component, OnInit, ChangeDetectionStrategy } from '@angular/core';

@Component({
  selector: 'app-ui-loading-spinner',
  templateUrl: './ui-loading-spinner.component.html',
  styleUrls: ['./ui-loading-spinner.component.sass'],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class UiLoadingSpinnerComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}

<div class="relative w-full h-full flex flex-col items-center justify-center animate-fade-in-tooltip">
  <div class="loader ease-linear rounded-full border-2 border-t-2 h-20 w-20"></div>
  <h2 class="font-semibold mt-2 absolute bottom-12 text-md">
    Loading...
  </h2>
  <small>Please wait</small>
</div>

// svelte/src/components/common/ui/UiLoadingSpinner.svelte
<div class="UiLoadingSpinner relative w-full h-full flex flex-col items-center justify-center animate-fade-in-tooltip">
  <div class="loader ease-linear rounded-full border-2 border-t-2 h-20 w-20" />
  <h2 class="font-semibold mt-2 absolute bottom-12 text-md">
  Loading...
  </h2>
  <small>Please wait</small>
</div>

<style lang="scss">
  @keyframes spinner {
    0% {
      transform: rotate(0deg);
    }
    100% {
      transform: rotate(360deg);
    }
  }
  
  .UiLoadingSpinner {
    .loader {
      @apply border-blue-200 border-t-blue-500;
      -webkit-animation: spinner 1s linear infinite;
      animation: spinner 1s linear infinite;
    }
  }
</style>
