// svelte/src/components/common/ui/UiLoadingContentWrapper.svelte
<script lang="ts">
import UiLoadingSpinner from './UiLoadingSpinner.svelte';

export let isLoading = false;
</script>

<div class="UiLoadingContentWrapper relative">
  {#if isLoading}
  <div class="absolute top-14 w-full animate-fade-in-down">
    <UiLoadingSpinner data-testid="ui-loading-spinner" />
  </div>
  {:else}
  <div>
    <slot />
  </div>
  {/if}
</div>

// angular/src/app/shared/components/ui/ui-loading-content-wrapper/ui-loading-content-wrapper.component.ts
import { Component, ChangeDetectionStrategy, Input } from '@angular/core';

@Component({
  selector: 'app-ui-loading-content-wrapper',
  templateUrl: './ui-loading-content-wrapper.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class UiLoadingContentWrapperComponent {
  @Input() isLoading: boolean = false;
}

<div class="UiLoadingContentWrapper relative">
  <div *ngIf="isLoading"
       class="absolute top-14 w-full animate-fade-in-down"
  >
    <app-ui-loading-spinner></app-ui-loading-spinner>
  </div>
  <div [class.opacity-5]="isLoading"
       [class.animate-fade-in-up]="!isLoading"
  >
    <ng-content></ng-content>
  </div>
</div>
